### ISSUE TITLE
Add Google App Script to send email onFormSubmit

### ISSUE THREAD

**Issue by mayknxyz** [mayknxyz/c5-gabs-trucking-com#3]

**Comment by kyooreasmayk** [comment]
- [x] Google Sheet: ["gabstrucking.com form (Responses)"](https://docs.google.com/spreadsheets/d/11ZFoW37qM8CsOW_YjgTOf6UGIgYnYuE024DCMyfg1u0/edit#gid=1303405132)
- [x] Google Form: ["gabstrucking.com form"](https://docs.google.com/forms/d/1lYVo0CJWHUotdHj9TdmzvSsxqwhV3TQ51bmtE6p3pv8/edit)
- [x] Google Apps Scripts: ["gabstrucking.com form (Responses)"](https://script.google.com/home/projects/13N-xcLYsfMVmc1GzNuJTJlvALcebByoXJcgqOH8qUBiFtX4eK2MyYzlr/edit)

**Comment by kyooreasmayk** [comment]
- [x] Add Script:

> ```
> function sendNew(){
>   var dataSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Form Responses 1");
>   var templetSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("template");
>   var templateSubject = templetSheet.getRange(1, 2).getValue();
>   var templateBody = templetSheet.getRange(2, 2).getValue();
> 
>   for (var i =2; i<= dataSheet.getLastRow(); i++){
> 
>     var status = dataSheet.getRange(i, 10).getValue();
> 
>     if (status == ""){
>       var
>         timeStamp = dataSheet.getRange(i, 1).getValue(),
>         name = dataSheet.getRange(i, 2).getValue(),
>         email = dataSheet.getRange(i, 3).getValue(),	
>         phoneNumber = dataSheet.getRange(i, 4).getValue(), 
>         pickupTime = dataSheet.getRange(i, 5).getValue(),	
>         pickupLocation = dataSheet.getRange(i, 6).getValue(),	
>         dropLocation = dataSheet.getRange(i, 7).getValue(),	
>         typeOfCargo = dataSheet.getRange(i, 8).getValue(),	
>         moreDetails = dataSheet.getRange(i, 9).getValue();
> 
>       var subject = templateSubject.replace("<<name>>", name);
>       var body = templateBody.replace("<<timeStamp>>", timeStamp);
>       body = body.replace("<<name>>", name);
>       body = body.replace("<<email>>", email);
>       body = body.replace("<<phoneNumber>>", phoneNumber);
>       body = body.replace("<<pickupTime>>", pickupTime);
>       body = body.replace("<<pickupLocation>>", pickupLocation);
>       body = body.replace("<<dropLocation>>", dropLocation);
>       body = body.replace("<<typeOfCargo>>", typeOfCargo);
>       body = body.replace("<<moreDetails>>", moreDetails);
> 
>    
>       MailApp.sendEmail('fritzjeraldgabayan@gmail.com, gabstrucking@gmail.com', subject, body);
>       dataSheet.getRange(i,10).setValue("Email Sent");
>     } 
>   }
> }
> ```

- [ ] Add trigger onFormSubmit
